version: '3.1'
services:
  app:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    volumes:
     - ./alarm-clock:/home/node
     - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
     - 8100:8100
    restart: always
    tty: true
    stdin_open: true
    environment:
     - DISPLAY=$DISPLAY
    privileged: true
